### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "6c86ea3cfae54c1a93e2c6ffc8701f14",
  "accountNumber": "1000000003",
  "amount": 2000
}

### query transaction
GET http://localhost:8080/transaction/6c86ea3cfae54c1a93e2c6ffc8701f14

